version: '3'
services:
  db:
    container_name: app-db
    image: postgres:14-alpine
    ports:
      - '54321:5432'
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    # volumes:
    #   - ../.docker/database:/var/lib/postgresql/data