version: '3'
services:
  db:
    container_name: sdn-db
    image: postgres:14-alpine
    ports:
      - '54321:5432'
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'

  migrate:
    container_name: sdn-migration
    build:
      context: ..
      dockerfile: Dockerfile.migration
    command: -dir migrations up
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=postgresql://postgres:postgres@db:5432/postgres?sslmode=disable
    volumes:
      - ../migrations:/migrations
    depends_on: [db]

  app:
    container_name: sdn-app
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres?sslmode=disable
    depends_on: [db]
    ports:
      - "8080:8080"